import { GpuDevice, SessionStats, SessionStatus, HashcatConfig } from './types';

export const INITIAL_DEVICES: GpuDevice[] = [
  { id: 1, name: 'Device #1', temp: 0, fanSpeed: 0, utilization: 0, coreClock: 0, memoryClock: 0 },
];

export const INITIAL_SESSION: SessionStats = {
  status: SessionStatus.IDLE,
  target: 'Waiting for config...',
  hashType: '--',
  progress: 0,
  recovered: 0,
  total: 0,
  hashrate: 0,
  estimatedTimeRemaining: '--:--:--',
  startTime: Date.now(),
  recoveredHashes: [] 
};

export const DEFAULT_CONFIG: HashcatConfig = {
  hashType: '0',
  attackMode: 0,
  
  devices: '',
  resourcesPath: '',
  
  targetPath: '', 
  wordlistPath: '',
  rulePath: '',
  mask: '?a?a?a?a?a?a?a',
  maskFile: '',
  
  // Increment Settings
  increment: false,
  incrementMin: 1,
  incrementMax: 8,
  incrementInverse: false,

  optimizedKernel: true,
  workloadProfile: 3,
  statusTimer: 30, 
  potfileDisable: false,
  remove: false,
  hwmonDisable: true,
  
  bitmapMax: 24,
  backendDisableOpenCL: false,
  backendIgnoreCuda: false,
  spinDamp: 100,
  scryptTmto: 0,
  segmentSize: 0,
  keepGuessing: false,
  selfTestDisable: false,
  logfileDisable: false,
  force: false,
  skip: 0,
};

export const ATTACK_MODES = [
  { id: 0, name: 'Straight (Dictionary)', desc: 'Standard wordlist attack' },
  { id: 1, name: 'Combination', desc: 'Combine two dictionaries' },
  { id: 3, name: 'Brute-Force', desc: 'Mask attack / Full keyspace' },
  { id: 6, name: 'Hybrid Dict + Mask', desc: 'Wordlist + Append mask' },
  { id: 7, name: 'Hybrid Mask + Dict', desc: 'Prepend mask + Wordlist' },
  { id: 9, name: 'Association', desc: 'Association attack' }
];

export const HASH_TYPES = [
  // --- Raw Hash ---
  { id: '900', name: 'MD4', category: 'Raw Hash' },
  { id: '0', name: 'MD5', category: 'Raw Hash' },
  { id: '34600', name: 'MD6 (256)', category: 'Raw Hash' },
  { id: '100', name: 'SHA1', category: 'Raw Hash' },
  { id: '1300', name: 'SHA2-224', category: 'Raw Hash' },
  { id: '1400', name: 'SHA2-256', category: 'Raw Hash' },
  { id: '10800', name: 'SHA2-384', category: 'Raw Hash' },
  { id: '1700', name: 'SHA2-512', category: 'Raw Hash' },
  { id: '17300', name: 'SHA3-224', category: 'Raw Hash' },
  { id: '17400', name: 'SHA3-256', category: 'Raw Hash' },
  { id: '17500', name: 'SHA3-384', category: 'Raw Hash' },
  { id: '17600', name: 'SHA3-512', category: 'Raw Hash' },
  { id: '6000', name: 'RIPEMD-160', category: 'Raw Hash' },
  { id: '33600', name: 'RIPEMD-320', category: 'Raw Hash' },
  { id: '34800', name: 'BLAKE2b-256', category: 'Raw Hash' },
  { id: '600', name: 'BLAKE2b-512', category: 'Raw Hash' },
  { id: '31000', name: 'BLAKE2s-256', category: 'Raw Hash' },
  { id: '11700', name: 'GOST R 34.11-2012 (Streebog) 256-bit, big-endian', category: 'Raw Hash' },
  { id: '11800', name: 'GOST R 34.11-2012 (Streebog) 512-bit, big-endian', category: 'Raw Hash' },
  { id: '6900', name: 'GOST R 34.11-94', category: 'Raw Hash' },
  { id: '5100', name: 'Half MD5', category: 'Raw Hash' },
  { id: '17700', name: 'Keccak-224', category: 'Raw Hash' },
  { id: '17800', name: 'Keccak-256', category: 'Raw Hash' },
  { id: '17900', name: 'Keccak-384', category: 'Raw Hash' },
  { id: '18000', name: 'Keccak-512', category: 'Raw Hash' },
  { id: '31100', name: 'ShangMi 3 (SM3)', category: 'Raw Hash' },
  { id: '6100', name: 'Whirlpool', category: 'Raw Hash' },
  { id: '70', name: 'md5(utf16le($pass))', category: 'Raw Hash' },
  { id: '170', name: 'sha1(utf16le($pass))', category: 'Raw Hash' },
  { id: '34500', name: 'sha224(sha1($pass))', category: 'Raw Hash' },
  { id: '34400', name: 'sha224(sha224($pass))', category: 'Raw Hash' },
  { id: '1470', name: 'sha256(utf16le($pass))', category: 'Raw Hash' },
  { id: '10870', name: 'sha384(utf16le($pass))', category: 'Raw Hash' },
  { id: '1770', name: 'sha512(utf16le($pass))', category: 'Raw Hash' },

  // --- Raw Hash salted and/or iterated ---
  { id: '34810', name: 'BLAKE2b-256($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '34820', name: 'BLAKE2b-256($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '610', name: 'BLAKE2b-512($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '620', name: 'BLAKE2b-512($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '10', name: 'md5($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '20', name: 'md5($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '3800', name: 'md5($salt.$pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '3710', name: 'md5($salt.md5($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '33100', name: 'md5($salt.md5($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '4110', name: 'md5($salt.md5($pass.$salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '4010', name: 'md5($salt.md5($salt.$pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '21300', name: 'md5($salt.sha1($salt.$pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '40', name: 'md5($salt.utf16le($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '33000', name: 'md5($salt1.$pass.$salt2)', category: 'Raw Hash salted and/or iterated' },
  { id: '21310', name: 'md5($salt1.sha1($salt2.$pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '3730', name: 'md5($salt1.strtoupper(md5($salt2.$pass)))', category: 'Raw Hash salted and/or iterated' },
  { id: '2600', name: 'md5(md5($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '3910', name: 'md5(md5($pass).md5($salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '2630', name: 'md5(md5($pass.$salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '30500', name: 'md5(md5($salt).md5(md5($pass)))', category: 'Raw Hash salted and/or iterated' },
  { id: '3500', name: 'md5(md5(md5($pass)))', category: 'Raw Hash salted and/or iterated' },
  { id: '3610', name: 'md5(md5(md5($pass)).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '31700', name: 'md5(md5(md5($pass).$salt1).$salt2)', category: 'Raw Hash salted and/or iterated' },
  { id: '21900', name: 'md5(md5(md5($pass.$salt1)).$salt2)', category: 'Raw Hash salted and/or iterated' },
  { id: '4400', name: 'md5(sha1($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '4410', name: 'md5(sha1($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '20900', name: 'md5(sha1($pass).md5($pass).sha1($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '4420', name: 'md5(sha1($pass.$salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '21200', name: 'md5(sha1($salt).md5($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '4430', name: 'md5(sha1($salt.$pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '32800', name: 'md5(sha1(md5($pass)))', category: 'Raw Hash salted and/or iterated' },
  { id: '4300', name: 'md5(strtoupper(md5($pass)))', category: 'Raw Hash salted and/or iterated' },
  { id: '30', name: 'md5(utf16le($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '110', name: 'sha1($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '120', name: 'sha1($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '4900', name: 'sha1($salt.$pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '4520', name: 'sha1($salt.sha1($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '24300', name: 'sha1($salt.sha1($pass.$salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '29000', name: 'sha1($salt.sha1(utf16le($username).: .utf16le($pass)))', category: 'Raw Hash salted and/or iterated' },
  { id: '140', name: 'sha1($salt.utf16le($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '19300', name: 'sha1($salt1.$pass.$salt2)', category: 'Raw Hash salted and/or iterated' },
  { id: '14400', name: 'sha1(CX)', category: 'Raw Hash salted and/or iterated' },
  { id: '4700', name: 'sha1(md5($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '4710', name: 'sha1(md5($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '21100', name: 'sha1(md5($pass.$salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '18500', name: 'sha1(md5(md5($pass)))', category: 'Raw Hash salted and/or iterated' },
  { id: '4500', name: 'sha1(sha1($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '4510', name: 'sha1(sha1($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '5000', name: 'sha1(sha1($salt.$pass.$salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '130', name: 'sha1(utf16le($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '1310', name: 'sha224($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '1320', name: 'sha224($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '1410', name: 'sha256($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '1420', name: 'sha256($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '22300', name: 'sha256($salt.$pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '20720', name: 'sha256($salt.sha256($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '21420', name: 'sha256($salt.sha256_bin($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '1440', name: 'sha256($salt.utf16le($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '20800', name: 'sha256(md5($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '20710', name: 'sha256(sha256($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '20730', name: 'sha256(sha256($pass.$salt))', category: 'Raw Hash salted and/or iterated' },
  { id: '21400', name: 'sha256(sha256_bin($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '1430', name: 'sha256(utf16le($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '10810', name: 'sha384($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '10820', name: 'sha384($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '10840', name: 'sha384($salt.utf16le($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '10830', name: 'sha384(utf16le($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '1710', name: 'sha512($pass.$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '1720', name: 'sha512($salt.$pass)', category: 'Raw Hash salted and/or iterated' },
  { id: '1740', name: 'sha512($salt.utf16le($pass))', category: 'Raw Hash salted and/or iterated' },
  { id: '32410', name: 'sha512(sha512($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '32420', name: 'sha512(sha512_bin($pass).$salt)', category: 'Raw Hash salted and/or iterated' },
  { id: '1730', name: 'sha512(utf16le($pass).$salt)', category: 'Raw Hash salted and/or iterated' },

  // --- Raw Hash authenticated ---
  { id: '33300', name: 'HMAC-BLAKE2S (key = $pass)', category: 'Raw Hash authenticated' },
  { id: '50', name: 'HMAC-MD5 (key = $pass)', category: 'Raw Hash authenticated' },
  { id: '60', name: 'HMAC-MD5 (key = $salt)', category: 'Raw Hash authenticated' },
  { id: '6050', name: 'HMAC-RIPEMD160 (key = $pass)', category: 'Raw Hash authenticated' },
  { id: '6060', name: 'HMAC-RIPEMD160 (key = $salt)', category: 'Raw Hash authenticated' },
  { id: '33650', name: 'HMAC-RIPEMD320 (key = $pass)', category: 'Raw Hash authenticated' },
  { id: '33660', name: 'HMAC-RIPEMD320 (key = $salt)', category: 'Raw Hash authenticated' },
  { id: '150', name: 'HMAC-SHA1 (key = $pass)', category: 'Raw Hash authenticated' },
  { id: '160', name: 'HMAC-SHA1 (key = $salt)', category: 'Raw Hash authenticated' },
  { id: '1450', name: 'HMAC-SHA256 (key = $pass)', category: 'Raw Hash authenticated' },
  { id: '1460', name: 'HMAC-SHA256 (key = $salt)', category: 'Raw Hash authenticated' },
  { id: '1750', name: 'HMAC-SHA512 (key = $pass)', category: 'Raw Hash authenticated' },
  { id: '1760', name: 'HMAC-SHA512 (key = $salt)', category: 'Raw Hash authenticated' },
  { id: '11750', name: 'HMAC-Streebog-256 (key = $pass), big-endian', category: 'Raw Hash authenticated' },
  { id: '11760', name: 'HMAC-Streebog-256 (key = $salt), big-endian', category: 'Raw Hash authenticated' },
  { id: '11850', name: 'HMAC-Streebog-512 (key = $pass), big-endian', category: 'Raw Hash authenticated' },
  { id: '11860', name: 'HMAC-Streebog-512 (key = $salt), big-endian', category: 'Raw Hash authenticated' },
  { id: '10100', name: 'SipHash', category: 'Raw Hash authenticated' },

  // --- Raw Checksum ---
  { id: '11500', name: 'CRC32', category: 'Raw Checksum' },
  { id: '27900', name: 'CRC32C', category: 'Raw Checksum' },
  { id: '28000', name: 'CRC64Jones', category: 'Raw Checksum' },
  { id: '18700', name: 'Java Object hashCode()', category: 'Raw Checksum' },
  { id: '25700', name: 'MurmurHash', category: 'Raw Checksum' },
  { id: '27800', name: 'MurmurHash3', category: 'Raw Checksum' },
  { id: '34200', name: 'MurmurHash64A', category: 'Raw Checksum' },
  { id: '34201', name: 'MurmurHash64A (zero seed)', category: 'Raw Checksum' },
  { id: '34211', name: 'MurmurHash64A truncated (zero seed)', category: 'Raw Checksum' },

  // --- Raw Cipher, Known-plaintext attack ---
  { id: '33502', name: 'RC4 104-bit DropN', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '33500', name: 'RC4 40-bit DropN', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '33501', name: 'RC4 72-bit DropN', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '14100', name: '3DES (PT = $salt, key = $pass)', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '14000', name: 'DES (PT = $salt, key = $pass)', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '26401', name: 'AES-128-ECB NOKDF (PT = $salt, key = $pass)', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '26402', name: 'AES-192-ECB NOKDF (PT = $salt, key = $pass)', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '26403', name: 'AES-256-ECB NOKDF (PT = $salt, key = $pass)', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '15400', name: 'ChaCha20', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '14500', name: 'Linux Kernel Crypto API (2.4)', category: 'Raw Cipher, Known-plaintext attack' },
  { id: '14900', name: 'Skip32 (PT = $salt, key = $pass)', category: 'Raw Cipher, Known-plaintext attack' },

  // --- Generic KDF ---
  { id: '32900', name: 'PBKDF1-SHA1', category: 'Generic KDF' },
  { id: '11900', name: 'PBKDF2-HMAC-MD5', category: 'Generic KDF' },
  { id: '12000', name: 'PBKDF2-HMAC-SHA1', category: 'Generic KDF' },
  { id: '10900', name: 'PBKDF2-HMAC-SHA256', category: 'Generic KDF' },
  { id: '12100', name: 'PBKDF2-HMAC-SHA512', category: 'Generic KDF' },
  { id: '34000', name: 'Argon2', category: 'Generic KDF' },
  { id: '70000', name: 'Argon2id [Bridged: reference implementation + tunings]', category: 'Generic KDF' },
  { id: '8900', name: 'scrypt', category: 'Generic KDF' },
  { id: '70100', name: 'scrypt [Bridged: Scrypt-Jane SMix]', category: 'Generic KDF' },
  { id: '70200', name: 'scrypt [Bridged: Scrypt-Yescrypt]', category: 'Generic KDF' },
  { id: '30601', name: 'bcrypt(HMAC-SHA256($pass))', category: 'Generic KDF' },
  { id: '25600', name: 'bcrypt(md5($pass))', category: 'Generic KDF' },
  { id: '25800', name: 'bcrypt(sha1($pass))', category: 'Generic KDF' },
  { id: '30600', name: 'bcrypt(sha256($pass))', category: 'Generic KDF' },
  { id: '28400', name: 'bcrypt(sha512($pass))', category: 'Generic KDF' },
  { id: '400', name: 'phpass', category: 'Generic KDF' },

  // --- Network Protocol ---
  { id: '16100', name: 'TACACS+', category: 'Network Protocol' },
  { id: '30420', name: 'DANE RFC7929/RFC8162 SHA2-256', category: 'Network Protocol' },
  { id: '11400', name: 'SIP digest authentication (MD5)', category: 'Network Protocol' },
  { id: '5300', name: 'IKE-PSK MD5', category: 'Network Protocol' },
  { id: '5400', name: 'IKE-PSK SHA1', category: 'Network Protocol' },
  { id: '25100', name: 'SNMPv3 HMAC-MD5-96', category: 'Network Protocol' },
  { id: '25000', name: 'SNMPv3 HMAC-MD5-96/HMAC-SHA1-96', category: 'Network Protocol' },
  { id: '25200', name: 'SNMPv3 HMAC-SHA1-96', category: 'Network Protocol' },
  { id: '26700', name: 'SNMPv3 HMAC-SHA224-128', category: 'Network Protocol' },
  { id: '26800', name: 'SNMPv3 HMAC-SHA256-192', category: 'Network Protocol' },
  { id: '26900', name: 'SNMPv3 HMAC-SHA384-256', category: 'Network Protocol' },
  { id: '27300', name: 'SNMPv3 HMAC-SHA512-384', category: 'Network Protocol' },
  { id: '2500', name: 'WPA-EAPOL-PBKDF2', category: 'Network Protocol' },
  { id: '2501', name: 'WPA-EAPOL-PMK', category: 'Network Protocol' },
  { id: '22000', name: 'WPA-PBKDF2-PMKID+EAPOL', category: 'Network Protocol' },
  { id: '22001', name: 'WPA-PMK-PMKID+EAPOL', category: 'Network Protocol' },
  { id: '16800', name: 'WPA-PMKID-PBKDF2', category: 'Network Protocol' },
  { id: '16801', name: 'WPA-PMKID-PMK', category: 'Network Protocol' },
  { id: '7350', name: 'IPMI2 RAKP HMAC-MD5', category: 'Network Protocol' },
  { id: '7300', name: 'IPMI2 RAKP HMAC-SHA1', category: 'Network Protocol' },
  { id: '10200', name: 'CRAM-MD5', category: 'Network Protocol' },
  { id: '31300', name: 'MS SNTP', category: 'Network Protocol' },
  { id: '16500', name: 'JWT (JSON Web Token)', category: 'Network Protocol' },
  { id: '19600', name: 'Kerberos 5, etype 17, TGS-REP', category: 'Network Protocol' },
  { id: '19800', name: 'Kerberos 5, etype 17, Pre-Auth', category: 'Network Protocol' },
  { id: '28800', name: 'Kerberos 5, etype 17, DB', category: 'Network Protocol' },
  { id: '32100', name: 'Kerberos 5, etype 17, AS-REP', category: 'Network Protocol' },
  { id: '19700', name: 'Kerberos 5, etype 18, TGS-REP', category: 'Network Protocol' },
  { id: '19900', name: 'Kerberos 5, etype 18, Pre-Auth', category: 'Network Protocol' },
  { id: '28900', name: 'Kerberos 5, etype 18, DB', category: 'Network Protocol' },
  { id: '32200', name: 'Kerberos 5, etype 18, AS-REP', category: 'Network Protocol' },
  { id: '7500', name: 'Kerberos 5, etype 23, AS-REQ Pre-Auth', category: 'Network Protocol' },
  { id: '13100', name: 'Kerberos 5, etype 23, TGS-REP', category: 'Network Protocol' },
  { id: '18200', name: 'Kerberos 5, etype 23, AS-REP', category: 'Network Protocol' },
  { id: '5500', name: 'NetNTLMv1 / NetNTLMv1+ESS', category: 'Network Protocol' },
  { id: '27000', name: 'NetNTLMv1 / NetNTLMv1+ESS (NT)', category: 'Network Protocol' },
  { id: '5600', name: 'NetNTLMv2', category: 'Network Protocol' },
  { id: '27100', name: 'NetNTLMv2 (NT)', category: 'Network Protocol' },
  { id: '29100', name: 'Flask Session Cookie ($salt.$salt.$pass)', category: 'Network Protocol' },
  { id: '28700', name: 'Amazon AWS Signature Version 4', category: 'Network Protocol' },
  { id: '4800', name: 'iSCSI CHAP authentication, MD5(CHAP)', category: 'Network Protocol' },

  // --- Operating System ---
  { id: '8500', name: 'RACF', category: 'Operating System' },
  { id: '14200', name: 'RACF KDFAES', category: 'Operating System' },
  { id: '6300', name: 'AIX {smd5}', category: 'Operating System' },
  { id: '6700', name: 'AIX {ssha1}', category: 'Operating System' },
  { id: '6400', name: 'AIX {ssha256}', category: 'Operating System' },
  { id: '6500', name: 'AIX {ssha512}', category: 'Operating System' },
  { id: '3000', name: 'LM', category: 'Operating System' },
  { id: '19000', name: 'QNX /etc/shadow (MD5)', category: 'Operating System' },
  { id: '19100', name: 'QNX /etc/shadow (SHA256)', category: 'Operating System' },
  { id: '19200', name: 'QNX /etc/shadow (SHA512)', category: 'Operating System' },
  { id: '19210', name: 'QNX 7 /etc/shadow (SHA512)', category: 'Operating System' },
  { id: '15300', name: 'DPAPI masterkey file v1 (context 1 and 2)', category: 'Operating System' },
  { id: '15310', name: 'DPAPI masterkey file v1 (context 3)', category: 'Operating System' },
  { id: '15900', name: 'DPAPI masterkey file v2 (context 1 and 2)', category: 'Operating System' },
  { id: '15910', name: 'DPAPI masterkey file v2 (context 3)', category: 'Operating System' },
  { id: '7200', name: 'GRUB 2', category: 'Operating System' },
  { id: '12800', name: 'MS-AzureSync PBKDF2-HMAC-SHA256', category: 'Operating System' },
  { id: '8501', name: 'AS/400 DES', category: 'Operating System' },
  { id: '35200', name: 'AS/400 SSHA1', category: 'Operating System' },
  { id: '12400', name: 'BSDi Crypt, Extended DES', category: 'Operating System' },
  { id: '1000', name: 'NTLM', category: 'Operating System' },
  { id: '9900', name: 'Radmin2', category: 'Operating System' },
  { id: '5800', name: 'Samsung Android Password/PIN', category: 'Operating System' },
  { id: '33700', name: 'Microsoft Online Account (PBKDF2-HMAC-SHA256 + AES256)', category: 'Operating System' },
  { id: '28100', name: 'Windows Hello PIN/Password', category: 'Operating System' },
  { id: '13800', name: 'Windows Phone 8+ PIN/password', category: 'Operating System' },
  { id: '2410', name: 'Cisco-ASA MD5', category: 'Operating System' },
  { id: '9200', name: 'Cisco-IOS $8$ (PBKDF2-SHA256)', category: 'Operating System' },
  { id: '9300', name: 'Cisco-IOS $9$ (scrypt)', category: 'Operating System' },
  { id: '5700', name: 'Cisco-IOS type 4 (SHA256)', category: 'Operating System' },
  { id: '5720', name: 'Cisco-ISE Hashed Password (SHA256)', category: 'Operating System' },
  { id: '2400', name: 'Cisco-PIX MD5', category: 'Operating System' },
  { id: '33900', name: 'Citrix NetScaler (PBKDF2-HMAC-SHA256)', category: 'Operating System' },
  { id: '8100', name: 'Citrix NetScaler (SHA1)', category: 'Operating System' },
  { id: '22200', name: 'Citrix NetScaler (SHA512)', category: 'Operating System' },
  { id: '1100', name: 'Domain Cached Credentials (DCC), MS Cache', category: 'Operating System' },
  { id: '2100', name: 'Domain Cached Credentials 2 (DCC2), MS Cache 2', category: 'Operating System' },
  { id: '31500', name: 'Domain Cached Credentials (DCC), MS Cache (NT)', category: 'Operating System' },
  { id: '31600', name: 'Domain Cached Credentials 2 (DCC2), MS Cache 2, (NT)', category: 'Operating System' },
  { id: '7000', name: 'FortiGate (FortiOS)', category: 'Operating System' },
  { id: '26300', name: 'FortiGate256 (FortiOS256)', category: 'Operating System' },
  { id: '125', name: 'ArubaOS', category: 'Operating System' },
  { id: '501', name: 'Juniper IVE', category: 'Operating System' },
  { id: '22', name: 'Juniper NetScreen/SSG (ScreenOS)', category: 'Operating System' },
  { id: '15100', name: 'Juniper/NetBSD sha1crypt', category: 'Operating System' },
  { id: '26500', name: 'iPhone passcode (UID key + System Keybag)', category: 'Operating System' },
  { id: '122', name: 'macOS v10.4, macOS v10.5, macOS v10.6', category: 'Operating System' },
  { id: '1722', name: 'macOS v10.7', category: 'Operating System' },
  { id: '7100', name: 'macOS v10.8+ (PBKDF2-SHA512)', category: 'Operating System' },
  { id: '3200', name: 'bcrypt $2*$, Blowfish (Unix)', category: 'Operating System' },
  { id: '500', name: 'md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)', category: 'Operating System' },
  { id: '1500', name: 'descrypt, DES (Unix), Traditional DES', category: 'Operating System' },
  { id: '7400', name: 'sha256crypt $5$, SHA256 (Unix)', category: 'Operating System' },
  { id: '1800', name: 'sha512crypt $6$, SHA512 (Unix)', category: 'Operating System' },
  { id: '35100', name: 'sm3crypt $sm3$, SM3 (Unix)', category: 'Operating System' },

  // --- Database Server ---
  { id: '131', name: 'MSSQL (2000)', category: 'Database Server' },
  { id: '132', name: 'MSSQL (2005)', category: 'Database Server' },
  { id: '1731', name: 'MSSQL (2012, 2014)', category: 'Database Server' },
  { id: '24100', name: 'MongoDB ServerKey SCRAM-SHA-1', category: 'Database Server' },
  { id: '24200', name: 'MongoDB ServerKey SCRAM-SHA-256', category: 'Database Server' },
  { id: '12', name: 'PostgreSQL', category: 'Database Server' },
  { id: '11100', name: 'PostgreSQL CRAM (MD5)', category: 'Database Server' },
  { id: '28600', name: 'PostgreSQL SCRAM-SHA-256', category: 'Database Server' },
  { id: '3100', name: 'Oracle H: Type (Oracle 7+)', category: 'Database Server' },
  { id: '112', name: 'Oracle S: Type (Oracle 11+)', category: 'Database Server' },
  { id: '12300', name: 'Oracle T: Type (Oracle 12+)', category: 'Database Server' },
  { id: '7401', name: 'MySQL $A$ (sha256crypt)', category: 'Database Server' },
  { id: '11200', name: 'MySQL CRAM (SHA1)', category: 'Database Server' },
  { id: '200', name: 'MySQL323', category: 'Database Server' },
  { id: '300', name: 'MySQL4.1/MySQL5', category: 'Database Server' },
  { id: '8000', name: 'Sybase ASE', category: 'Database Server' },

  // --- FTP, HTTP, SMTP, LDAP Server ---
  { id: '8300', name: 'DNSSEC (NSEC3)', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '25900', name: 'KNX IP Secure - Device Authentication Code', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '16400', name: 'CRAM-MD5 Dovecot', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '1411', name: 'SSHA-256(Base64), LDAP {SSHA256}', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '1711', name: 'SSHA-512(Base64), LDAP {SSHA512}', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '29200', name: 'Radmin3', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '24900', name: 'Dahua Authentication MD5', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '10901', name: 'RedHat 389-DS LDAP (PBKDF2-HMAC-SHA256)', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '24901', name: 'Besder Authentication MD5', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '15000', name: 'FileZilla Server >= 0.9.55', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '12600', name: 'ColdFusion 10+', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '1600', name: 'Apache $apr1$ MD5, md5apr1, MD5 (APR)', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '141', name: 'Episerver 6.x < .NET 4', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '1441', name: 'Episerver 6.x >= .NET 4', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '1421', name: 'hMailServer', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '101', name: 'nsldap, SHA-1(Base64), Netscape LDAP SHA', category: 'FTP, HTTP, SMTP, LDAP Server' },
  { id: '111', name: 'nsldaps, SSHA-1(Base64), Netscape LDAP SSHA', category: 'FTP, HTTP, SMTP, LDAP Server' },

  // --- Enterprise Application Software (EAS) ---
  { id: '7700', name: 'SAP CODVN B (BCODE)', category: 'Enterprise Application Software (EAS)' },
  { id: '7701', name: 'SAP CODVN B (BCODE) from RFC_READ_TABLE', category: 'Enterprise Application Software (EAS)' },
  { id: '7800', name: 'SAP CODVN F/G (PASSCODE)', category: 'Enterprise Application Software (EAS)' },
  { id: '7801', name: 'SAP CODVN F/G (PASSCODE) from RFC_READ_TABLE', category: 'Enterprise Application Software (EAS)' },
  { id: '10300', name: 'SAP CODVN H (PWDSALTEDHASH) iSSHA-1', category: 'Enterprise Application Software (EAS)' },
  { id: '35000', name: 'SAP CODVN H (PWDSALTEDHASH) isSHA512', category: 'Enterprise Application Software (EAS)' },
  { id: '20712', name: 'RSA Security Analytics / NetWitness (sha256)', category: 'Enterprise Application Software (EAS)' },
  { id: '32031', name: 'Adobe AEM (SSPR, SHA-256 with Salt)', category: 'Enterprise Application Software (EAS)' },
  { id: '32041', name: 'Adobe AEM (SSPR, SHA-512 with Salt)', category: 'Enterprise Application Software (EAS)' },
  { id: '133', name: 'PeopleSoft', category: 'Enterprise Application Software (EAS)' },
  { id: '13500', name: 'PeopleSoft PS_TOKEN', category: 'Enterprise Application Software (EAS)' },
  { id: '32000', name: 'NetIQ SSPR (MD5)', category: 'Enterprise Application Software (EAS)' },
  { id: '32050', name: 'NetIQ SSPR (PBKDF2WithHmacSHA1)', category: 'Enterprise Application Software (EAS)' },
  { id: '32060', name: 'NetIQ SSPR (PBKDF2WithHmacSHA256)', category: 'Enterprise Application Software (EAS)' },
  { id: '32070', name: 'NetIQ SSPR (PBKDF2WithHmacSHA512)', category: 'Enterprise Application Software (EAS)' },
  { id: '32020', name: 'NetIQ SSPR (SHA-1 with Salt)', category: 'Enterprise Application Software (EAS)' },
  { id: '32030', name: 'NetIQ SSPR (SHA-256 with Salt)', category: 'Enterprise Application Software (EAS)' },
  { id: '32040', name: 'NetIQ SSPR (SHA-512 with Salt)', category: 'Enterprise Application Software (EAS)' },
  { id: '32010', name: 'NetIQ SSPR (SHA1)', category: 'Enterprise Application Software (EAS)' },
  { id: '21500', name: 'SolarWinds Orion', category: 'Enterprise Application Software (EAS)' },
  { id: '21501', name: 'SolarWinds Orion v2', category: 'Enterprise Application Software (EAS)' },
  { id: '24', name: 'SolarWinds Serv-U', category: 'Enterprise Application Software (EAS)' },
  { id: '8600', name: 'Lotus Notes/Domino 5', category: 'Enterprise Application Software (EAS)' },
  { id: '8700', name: 'Lotus Notes/Domino 6', category: 'Enterprise Application Software (EAS)' },
  { id: '9100', name: 'Lotus Notes/Domino 8', category: 'Enterprise Application Software (EAS)' },
  { id: '26200', name: 'OpenEdge Progress Encode', category: 'Enterprise Application Software (EAS)' },
  { id: '20600', name: 'Oracle Transportation Management (SHA256)', category: 'Enterprise Application Software (EAS)' },
  { id: '4711', name: 'Huawei sha1(md5($pass).$salt)', category: 'Enterprise Application Software (EAS)' },
  { id: '20711', name: 'AuthMe sha256', category: 'Enterprise Application Software (EAS)' },

  // --- Full-Disk Encryption (FDE) ---
  { id: '22400', name: 'AES Crypt (SHA256)', category: 'Full-Disk Encryption (FDE)' },
  { id: '27400', name: 'VMware VMX (PBKDF2-HMAC-SHA1 + AES-256-CBC)', category: 'Full-Disk Encryption (FDE)' },
  { id: '14600', name: 'LUKS v1 (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29541', name: 'LUKS v1 RIPEMD-160 + AES', category: 'Full-Disk Encryption (FDE)' },
  { id: '29542', name: 'LUKS v1 RIPEMD-160 + Serpent', category: 'Full-Disk Encryption (FDE)' },
  { id: '29543', name: 'LUKS v1 RIPEMD-160 + Twofish', category: 'Full-Disk Encryption (FDE)' },
  { id: '29511', name: 'LUKS v1 SHA-1 + AES', category: 'Full-Disk Encryption (FDE)' },
  { id: '29512', name: 'LUKS v1 SHA-1 + Serpent', category: 'Full-Disk Encryption (FDE)' },
  { id: '29513', name: 'LUKS v1 SHA-1 + Twofish', category: 'Full-Disk Encryption (FDE)' },
  { id: '29521', name: 'LUKS v1 SHA-256 + AES', category: 'Full-Disk Encryption (FDE)' },
  { id: '29522', name: 'LUKS v1 SHA-256 + Serpent', category: 'Full-Disk Encryption (FDE)' },
  { id: '29523', name: 'LUKS v1 SHA-256 + Twofish', category: 'Full-Disk Encryption (FDE)' },
  { id: '29531', name: 'LUKS v1 SHA-512 + AES', category: 'Full-Disk Encryption (FDE)' },
  { id: '29532', name: 'LUKS v1 SHA-512 + Serpent', category: 'Full-Disk Encryption (FDE)' },
  { id: '29533', name: 'LUKS v1 SHA-512 + Twofish', category: 'Full-Disk Encryption (FDE)' },
  { id: '34100', name: 'LUKS v2 argon2 + SHA-256 + AES', category: 'Full-Disk Encryption (FDE)' },
  { id: '13711', name: 'VeraCrypt RIPEMD160 + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13712', name: 'VeraCrypt RIPEMD160 + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13713', name: 'VeraCrypt RIPEMD160 + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13741', name: 'VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13742', name: 'VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13743', name: 'VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29411', name: 'VeraCrypt RIPEMD160 + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29412', name: 'VeraCrypt RIPEMD160 + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29413', name: 'VeraCrypt RIPEMD160 + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29441', name: 'VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29442', name: 'VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29443', name: 'VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '13751', name: 'VeraCrypt SHA256 + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13752', name: 'VeraCrypt SHA256 + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13753', name: 'VeraCrypt SHA256 + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13761', name: 'VeraCrypt SHA256 + XTS 512 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13762', name: 'VeraCrypt SHA256 + XTS 1024 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13763', name: 'VeraCrypt SHA256 + XTS 1536 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29451', name: 'VeraCrypt SHA256 + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29452', name: 'VeraCrypt SHA256 + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29453', name: 'VeraCrypt SHA256 + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29461', name: 'VeraCrypt SHA256 + XTS 512 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29462', name: 'VeraCrypt SHA256 + XTS 1024 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29463', name: 'VeraCrypt SHA256 + XTS 1536 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '13721', name: 'VeraCrypt SHA512 + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13722', name: 'VeraCrypt SHA512 + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13723', name: 'VeraCrypt SHA512 + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29421', name: 'VeraCrypt SHA512 + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29422', name: 'VeraCrypt SHA512 + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29423', name: 'VeraCrypt SHA512 + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '13771', name: 'VeraCrypt Streebog-512 + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13772', name: 'VeraCrypt Streebog-512 + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13773', name: 'VeraCrypt Streebog-512 + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13781', name: 'VeraCrypt Streebog-512 + XTS 512 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13782', name: 'VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13783', name: 'VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29471', name: 'VeraCrypt Streebog-512 + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29472', name: 'VeraCrypt Streebog-512 + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29473', name: 'VeraCrypt Streebog-512 + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29481', name: 'VeraCrypt Streebog-512 + XTS 512 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29482', name: 'VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29483', name: 'VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '13731', name: 'VeraCrypt Whirlpool + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13732', name: 'VeraCrypt Whirlpool + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '13733', name: 'VeraCrypt Whirlpool + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29431', name: 'VeraCrypt Whirlpool + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29432', name: 'VeraCrypt Whirlpool + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29433', name: 'VeraCrypt Whirlpool + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '23900', name: 'BestCrypt v3 Volume Encryption', category: 'Full-Disk Encryption (FDE)' },
  { id: '24000', name: 'BestCrypt v4 Volume Encryption', category: 'Full-Disk Encryption (FDE)' },
  { id: '16700', name: 'FileVault 2', category: 'Full-Disk Encryption (FDE)' },
  { id: '27500', name: 'VirtualBox (PBKDF2-HMAC-SHA256 & AES-128-XTS)', category: 'Full-Disk Encryption (FDE)' },
  { id: '27600', name: 'VirtualBox (PBKDF2-HMAC-SHA256 & AES-256-XTS)', category: 'Full-Disk Encryption (FDE)' },
  { id: '20011', name: 'DiskCryptor SHA512 + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '20012', name: 'DiskCryptor SHA512 + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '20013', name: 'DiskCryptor SHA512 + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '22100', name: 'BitLocker', category: 'Full-Disk Encryption (FDE)' },
  { id: '12900', name: 'Android FDE (Samsung DEK)', category: 'Full-Disk Encryption (FDE)' },
  { id: '8800', name: 'Android FDE <= 4.3', category: 'Full-Disk Encryption (FDE)' },
  { id: '18300', name: 'Apple File System (APFS)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6211', name: 'TrueCrypt RIPEMD160 + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6212', name: 'TrueCrypt RIPEMD160 + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6213', name: 'TrueCrypt RIPEMD160 + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6241', name: 'TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6242', name: 'TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6243', name: 'TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29311', name: 'TrueCrypt RIPEMD160 + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29312', name: 'TrueCrypt RIPEMD160 + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29313', name: 'TrueCrypt RIPEMD160 + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29341', name: 'TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29342', name: 'TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '29343', name: 'TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode', category: 'Full-Disk Encryption (FDE)' },
  { id: '6221', name: 'TrueCrypt SHA512 + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6222', name: 'TrueCrypt SHA512 + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6223', name: 'TrueCrypt SHA512 + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29321', name: 'TrueCrypt SHA512 + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29322', name: 'TrueCrypt SHA512 + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29323', name: 'TrueCrypt SHA512 + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '6231', name: 'TrueCrypt Whirlpool + XTS 512 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6232', name: 'TrueCrypt Whirlpool + XTS 1024 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '6233', name: 'TrueCrypt Whirlpool + XTS 1536 bit (legacy)', category: 'Full-Disk Encryption (FDE)' },
  { id: '29331', name: 'TrueCrypt Whirlpool + XTS 512 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29332', name: 'TrueCrypt Whirlpool + XTS 1024 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '29333', name: 'TrueCrypt Whirlpool + XTS 1536 bit', category: 'Full-Disk Encryption (FDE)' },
  { id: '12200', name: 'eCryptfs', category: 'Full-Disk Encryption (FDE)' },

  // --- Document ---
  { id: '10400', name: 'PDF 1.1 - 1.3 (Acrobat 2 - 4)', category: 'Document' },
  { id: '10410', name: 'PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #1', category: 'Document' },
  { id: '10420', name: 'PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #2', category: 'Document' },
  { id: '10510', name: 'PDF 1.3 - 1.6 (Acrobat 4 - 8) w/ RC4-40', category: 'Document' },
  { id: '10500', name: 'PDF 1.4 - 1.6 (Acrobat 5 - 8)', category: 'Document' },
  { id: '25400', name: 'PDF 1.4 - 1.6 (Acrobat 5 - 8) - user and owner pass', category: 'Document' },
  { id: '10600', name: 'PDF 1.7 Level 3 (Acrobat 9)', category: 'Document' },
  { id: '10700', name: 'PDF 1.7 Level 8 (Acrobat 10 - 11)', category: 'Document' },
  { id: '9400', name: 'MS Office 2007', category: 'Document' },
  { id: '9500', name: 'MS Office 2010', category: 'Document' },
  { id: '9600', name: 'MS Office 2013', category: 'Document' },
  { id: '25300', name: 'MS Office 2016 - SheetProtection', category: 'Document' },
  { id: '9700', name: 'MS Office <= 2003 $0/$1, MD5 + RC4', category: 'Document' },
  { id: '9710', name: 'MS Office <= 2003 $0/$1, MD5 + RC4, collider #1', category: 'Document' },
  { id: '9720', name: 'MS Office <= 2003 $0/$1, MD5 + RC4, collider #2', category: 'Document' },
  { id: '9810', name: 'MS Office <= 2003 $3, SHA1 + RC4, collider #1', category: 'Document' },
  { id: '9820', name: 'MS Office <= 2003 $3, SHA1 + RC4, collider #2', category: 'Document' },
  { id: '9800', name: 'MS Office <= 2003 $3/$4, SHA1 + RC4', category: 'Document' },
  { id: '18400', name: 'Open Document Format (ODF) 1.2 (SHA-256, AES)', category: 'Document' },
  { id: '18600', name: 'Open Document Format (ODF) 1.1 (SHA-1, Blowfish)', category: 'Document' },
  { id: '16200', name: 'Apple Secure Notes', category: 'Document' },
  { id: '23300', name: 'Apple iWork', category: 'Document' },

  // --- Password Manager ---
  { id: '6600', name: '1Password, agilekeychain', category: 'Password Manager' },
  { id: '8200', name: '1Password, cloudkeychain', category: 'Password Manager' },
  { id: '31800', name: '1Password, mobilekeychain (1Password 8)', category: 'Password Manager' },
  { id: '9000', name: 'Password Safe v2', category: 'Password Manager' },
  { id: '5200', name: 'Password Safe v3', category: 'Password Manager' },
  { id: '6800', name: 'LastPass + LastPass sniffed', category: 'Password Manager' },
  { id: '13400', name: 'KeePass (KDBX v2/v3)', category: 'Password Manager' },
  { id: '29700', name: 'KeePass (KDBX v2/v3) - keyfile only', category: 'Password Manager' },
  { id: '34300', name: 'KeePass (KDBX v4)', category: 'Password Manager' },
  { id: '23400', name: 'Bitwarden', category: 'Password Manager' },
  { id: '16900', name: 'Ansible Vault', category: 'Password Manager' },
  { id: '26000', name: 'Mozilla key3.db', category: 'Password Manager' },
  { id: '26100', name: 'Mozilla key4.db', category: 'Password Manager' },
  { id: '23100', name: 'Apple Keychain', category: 'Password Manager' },

  // --- Archive ---
  { id: '11600', name: '7-Zip', category: 'Archive' },
  { id: '12500', name: 'RAR3-hp', category: 'Archive' },
  { id: '23800', name: 'RAR3-p (Compressed)', category: 'Archive' },
  { id: '23700', name: 'RAR3-p (Uncompressed)', category: 'Archive' },
  { id: '13000', name: 'RAR5', category: 'Archive' },
  { id: '17220', name: 'PKZIP (Compressed Multi-File)', category: 'Archive' },
  { id: '17200', name: 'PKZIP (Compressed)', category: 'Archive' },
  { id: '17225', name: 'PKZIP (Mixed Multi-File)', category: 'Archive' },
  { id: '17230', name: 'PKZIP (Mixed Multi-File Checksum-Only)', category: 'Archive' },
  { id: '17210', name: 'PKZIP (Uncompressed)', category: 'Archive' },
  { id: '20500', name: 'PKZIP Master Key', category: 'Archive' },
  { id: '20510', name: 'PKZIP Master Key (6 byte optimization)', category: 'Archive' },
  { id: '23001', name: 'SecureZIP AES-128', category: 'Archive' },
  { id: '23002', name: 'SecureZIP AES-192', category: 'Archive' },
  { id: '23003', name: 'SecureZIP AES-256', category: 'Archive' },
  { id: '31200', name: 'Veeam VBK', category: 'Archive' },
  { id: '13600', name: 'WinZip', category: 'Archive' },
  { id: '18900', name: 'Android Backup', category: 'Archive' },
  { id: '32700', name: 'Kremlin Encrypt 3.0 w/NewDES', category: 'Archive' },
  { id: '24700', name: 'Stuffit5', category: 'Archive' },
  { id: '13200', name: 'AxCrypt 1', category: 'Archive' },
  { id: '13300', name: 'AxCrypt 1 in-memory SHA1', category: 'Archive' },
  { id: '23500', name: 'AxCrypt 2 AES-128', category: 'Archive' },
  { id: '23600', name: 'AxCrypt 2 AES-256', category: 'Archive' },
  { id: '14700', name: 'iTunes backup < 10.0', category: 'Archive' },
  { id: '14800', name: 'iTunes backup >= 10.0', category: 'Archive' },
  { id: '33400', name: 'mega.nz password-protected link (PBKDF2-HMAC-SHA512)', category: 'Archive' },

  // --- Forums, CMS, E-Commerce ---
  { id: '8400', name: 'WBB3 (Woltlab Burning Board)', category: 'Forums, CMS, E-Commerce' },
  { id: '33800', name: 'WBB4 (Woltlab Burning Board) [bcrypt(bcrypt($pass))]', category: 'Forums, CMS, E-Commerce' },
  { id: '2612', name: 'PHPS', category: 'Forums, CMS, E-Commerce' },
  { id: '121', name: 'SMF (Simple Machines Forum) > v1.1', category: 'Forums, CMS, E-Commerce' },
  { id: '3711', name: 'MediaWiki B type', category: 'Forums, CMS, E-Commerce' },
  { id: '4521', name: 'Redmine', category: 'Forums, CMS, E-Commerce' },
  { id: '22800', name: 'Simpla CMS - md5($salt.$pass.md5($pass))', category: 'Forums, CMS, E-Commerce' },
  { id: '24800', name: 'Umbraco HMAC-SHA1', category: 'Forums, CMS, E-Commerce' },
  { id: '32300', name: 'Empire CMS (Admin password)', category: 'Forums, CMS, E-Commerce' },
  { id: '11', name: 'Joomla < 2.5.18', category: 'Forums, CMS, E-Commerce' },
  { id: '13900', name: 'OpenCart', category: 'Forums, CMS, E-Commerce' },
  { id: '11000', name: 'PrestaShop', category: 'Forums, CMS, E-Commerce' },
  { id: '16000', name: 'Tripcode', category: 'Forums, CMS, E-Commerce' },
  { id: '7900', name: 'Drupal7', category: 'Forums, CMS, E-Commerce' },
  { id: '32600', name: 'CubeCart (whirlpool($salt.$pass.$salt))', category: 'Forums, CMS, E-Commerce' },
  { id: '4522', name: 'PunBB', category: 'Forums, CMS, E-Commerce' },
  { id: '2811', name: 'MyBB 1.2+, IPB2+ (Invision Power Board)', category: 'Forums, CMS, E-Commerce' },
  { id: '2611', name: 'vBulletin < v3.8.5', category: 'Forums, CMS, E-Commerce' },
  { id: '2711', name: 'vBulletin >= v3.8.5', category: 'Forums, CMS, E-Commerce' },
  { id: '21', name: 'osCommerce, xt:Commerce', category: 'Forums, CMS, E-Commerce' },

  // --- One-Time Password ---
  { id: '18100', name: 'TOTP (HMAC-SHA1)', category: 'One-Time Password' },

  // --- Plaintext ---
  { id: '2000', name: 'STDOUT', category: 'Plaintext' },
  { id: '99999', name: 'Plaintext', category: 'Plaintext' },

  // --- Framework ---
  { id: '21600', name: 'Web2py pbkdf2-sha512', category: 'Framework' },
  { id: '16501', name: 'Perl Mojolicious session cookie (HMAC-SHA256, >= v9.19)', category: 'Framework' },
  { id: '10000', name: 'Django (PBKDF2-SHA256)', category: 'Framework' },
  { id: '124', name: 'Django (SHA-1)', category: 'Framework' },
  { id: '12150', name: 'Apache Shiro 1 SHA-512', category: 'Framework' },
  { id: '12001', name: 'Atlassian (PBKDF2-HMAC-SHA1)', category: 'Framework' },
  { id: '19500', name: 'Ruby on Rails Restful-Authentication', category: 'Framework' },
  { id: '27200', name: 'Ruby on Rails Restful Auth (one round, no sitekey)', category: 'Framework' },
  { id: '30000', name: 'Python Werkzeug MD5 (HMAC-MD5 (key = $salt))', category: 'Framework' },
  { id: '30120', name: 'Python Werkzeug SHA256 (HMAC-SHA256 (key = $salt))', category: 'Framework' },
  { id: '20200', name: 'Python passlib pbkdf2-sha512', category: 'Framework' },
  { id: '20300', name: 'Python passlib pbkdf2-sha256', category: 'Framework' },
  { id: '20400', name: 'Python passlib pbkdf2-sha1', category: 'Framework' },

  // --- Private Key ---
  { id: '24410', name: 'PKCS#8 Private Keys (PBKDF2-HMAC-SHA1 + 3DES/AES)', category: 'Private Key' },
  { id: '24420', name: 'PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES)', category: 'Private Key' },
  { id: '15500', name: 'JKS Java Key Store Private Keys (SHA1)', category: 'Private Key' },
  { id: '17010', name: 'GPG (AES-128/AES-256 (SHA-1($pass)))', category: 'Private Key' },
  { id: '17020', name: 'GPG (AES-128/AES-256 (SHA-512($pass)))', category: 'Private Key' },
  { id: '17030', name: 'GPG (AES-128/AES-256 (SHA-256($pass)))', category: 'Private Key' },
  { id: '17040', name: 'GPG (CAST5 (SHA-1($pass)))', category: 'Private Key' },
  { id: '22911', name: 'RSA/DSA/EC/OpenSSH Private Keys ($0$)', category: 'Private Key' },
  { id: '22921', name: 'RSA/DSA/EC/OpenSSH Private Keys ($6$)', category: 'Private Key' },
  { id: '22931', name: 'RSA/DSA/EC/OpenSSH Private Keys ($1, $3$)', category: 'Private Key' },
  { id: '22941', name: 'RSA/DSA/EC/OpenSSH Private Keys ($4$)', category: 'Private Key' },
  { id: '22951', name: 'RSA/DSA/EC/OpenSSH Private Keys ($5$)', category: 'Private Key' },

  // --- Instant Messaging Service ---
  { id: '23200', name: 'XMPP SCRAM PBKDF2-SHA1', category: 'Instant Messaging Service' },
  { id: '28300', name: 'Teamspeak 3 (channel hash)', category: 'Instant Messaging Service' },
  { id: '22600', name: 'Telegram Desktop < v2.1.14 (PBKDF2-HMAC-SHA1)', category: 'Instant Messaging Service' },
  { id: '24500', name: 'Telegram Desktop >= v2.1.14 (PBKDF2-HMAC-SHA512)', category: 'Instant Messaging Service' },
  { id: '22301', name: 'Telegram Mobile App Passcode (SHA256)', category: 'Instant Messaging Service' },
  { id: '23', name: 'Skype', category: 'Instant Messaging Service' },
  { id: '30700', name: 'Anope IRC Services (enc_sha256)', category: 'Instant Messaging Service' },

  // --- Cryptocurrency Wallet ---
  { id: '29600', name: 'Terra Station Wallet (AES256-CBC(PBKDF2($pass)))', category: 'Cryptocurrency Wallet' },
  { id: '31900', name: 'MetaMask Mobile Wallet', category: 'Cryptocurrency Wallet' },
  { id: '26600', name: 'MetaMask Wallet (needs all data, checks AES-GCM tag)', category: 'Cryptocurrency Wallet' },
  { id: '26610', name: 'MetaMask Wallet (short hash, plaintext check)', category: 'Cryptocurrency Wallet' },
  { id: '29800', name: 'Bisq .wallet (scrypt)', category: 'Cryptocurrency Wallet' },
  { id: '21000', name: 'BitShares v0.x - sha512(sha512_bin(pass))', category: 'Cryptocurrency Wallet' },
  { id: '28501', name: 'Bitcoin WIF private key (P2PKH), compressed', category: 'Cryptocurrency Wallet' },
  { id: '28502', name: 'Bitcoin WIF private key (P2PKH), uncompressed', category: 'Cryptocurrency Wallet' },
  { id: '28503', name: 'Bitcoin WIF private key (P2WPKH, Bech32), compressed', category: 'Cryptocurrency Wallet' },
  { id: '28504', name: 'Bitcoin WIF private key (P2WPKH, Bech32), uncompressed', category: 'Cryptocurrency Wallet' },
  { id: '28505', name: 'Bitcoin WIF private key (P2SH(P2WPKH)), compressed', category: 'Cryptocurrency Wallet' },
  { id: '28506', name: 'Bitcoin WIF private key (P2SH(P2WPKH)), uncompressed', category: 'Cryptocurrency Wallet' },
  { id: '30901', name: 'Bitcoin raw private key (P2PKH), compressed', category: 'Cryptocurrency Wallet' },
  { id: '30902', name: 'Bitcoin raw private key (P2PKH), uncompressed', category: 'Cryptocurrency Wallet' },
  { id: '30903', name: 'Bitcoin raw private key (P2WPKH, Bech32), compressed', category: 'Cryptocurrency Wallet' },
  { id: '30904', name: 'Bitcoin raw private key (P2WPKH, Bech32), uncompressed', category: 'Cryptocurrency Wallet' },
  { id: '30905', name: 'Bitcoin raw private key (P2SH(P2WPKH)), compressed', category: 'Cryptocurrency Wallet' },
  { id: '30906', name: 'Bitcoin raw private key (P2SH(P2WPKH)), uncompressed', category: 'Cryptocurrency Wallet' },
  { id: '11300', name: 'Bitcoin/Litecoin wallet.dat', category: 'Cryptocurrency Wallet' },
  { id: '16600', name: 'Electrum Wallet (Salt-Type 1-3)', category: 'Cryptocurrency Wallet' },
  { id: '21700', name: 'Electrum Wallet (Salt-Type 4)', category: 'Cryptocurrency Wallet' },
  { id: '21800', name: 'Electrum Wallet (Salt-Type 5)', category: 'Cryptocurrency Wallet' },
  { id: '12700', name: 'Blockchain, My Wallet', category: 'Cryptocurrency Wallet' },
  { id: '15200', name: 'Blockchain, My Wallet, V2', category: 'Cryptocurrency Wallet' },
  { id: '18800', name: 'Blockchain, My Wallet, Second Password (SHA256)', category: 'Cryptocurrency Wallet' },
  { id: '34700', name: 'Blockchain, My Wallet, Legacy Wallets', category: 'Cryptocurrency Wallet' },
  { id: '32500', name: 'Dogechain.info Wallet', category: 'Cryptocurrency Wallet' },
  { id: '25500', name: 'Stargazer Stellar Wallet XLM', category: 'Cryptocurrency Wallet' },
  { id: '16300', name: 'Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256', category: 'Cryptocurrency Wallet' },
  { id: '15600', name: 'Ethereum Wallet, PBKDF2-HMAC-SHA256', category: 'Cryptocurrency Wallet' },
  { id: '15700', name: 'Ethereum Wallet, SCRYPT', category: 'Cryptocurrency Wallet' },
  { id: '22500', name: 'MultiBit Classic .key (MD5)', category: 'Cryptocurrency Wallet' },
  { id: '27700', name: 'MultiBit Classic .wallet (scrypt)', category: 'Cryptocurrency Wallet' },
  { id: '22700', name: 'MultiBit HD (scrypt)', category: 'Cryptocurrency Wallet' },
  { id: '28200', name: 'Exodus Desktop Wallet (scrypt)', category: 'Cryptocurrency Wallet' },

  // --- File-Based Encryption (FBE) ---
  { id: '29910', name: 'ENCsecurity Datavault (PBKDF2/no keychain)', category: 'File-Based Encryption (FBE)' },
  { id: '29920', name: 'ENCsecurity Datavault (PBKDF2/keychain)', category: 'File-Based Encryption (FBE)' },
  { id: '29930', name: 'ENCsecurity Datavault (MD5/no keychain)', category: 'File-Based Encryption (FBE)' },
  { id: '29940', name: 'ENCsecurity Datavault (MD5/keychain)', category: 'File-Based Encryption (FBE)' },

  // --- Application Database ---
  { id: '24600', name: 'SQLCipher', category: 'Application Database' },
  { id: '31400', name: 'SecureCRT MasterPassphrase v2', category: 'Application Database' },

  // --- Undefined ---
  { id: '72000', name: 'Generic Hash [Bridged: Python Interpreter free-threading]', category: 'Undefined' },
  { id: '73000', name: 'Generic Hash [Bridged: Python Interpreter with GIL]', category: 'Undefined' },
  { id: '74000', name: 'Generic Hash [Bridged: Rust]', category: 'Undefined' }
];