import { GpuDevice, SessionStats, SessionStatus, HashcatConfig } from './types';

export const INITIAL_DEVICES: GpuDevice[] = [
  { id: 1, name: 'Device #1', temp: 0, fanSpeed: 0, utilization: 0, coreClock: 0, memoryClock: 0 },
];

export const INITIAL_SESSION: SessionStats = {
  status: SessionStatus.IDLE,
  target: 'Waiting for config...',
  hashType: 'SHA-256',
  progress: 0,
  recovered: 0,
  total: 0,
  hashrate: 0,
  estimatedTimeRemaining: '--:--:--',
  startTime: Date.now()
};

export const DEFAULT_CONFIG: HashcatConfig = {
  hashType: '0',
  attackMode: 0,
  targetPath: '', // Fixed: Added required targetPath
  wordlistPath: '',
  rulePath: '',
  mask: '?a?a?a?a?a?a?a',
  maskFile: '',
  
  optimizedKernel: true,
  workloadProfile: 3,
  statusTimer: 30, // Default 30 seconds as requested
  potfileDisable: false,
  remove: false,
  hwmonDisable: true,
  
  bitmapMax: 24,
  backendDisableOpenCL: false,
  backendIgnoreCuda: false,
  spinDamp: 100,
  scryptTmto: 0,
  segmentSize: 0,
  keepGuessing: false,
  selfTestDisable: false,
  logfileDisable: false,
  force: false,
  skip: 0,
};

export const ATTACK_MODES = [
  { id: 0, name: 'Straight (Dictionary)', desc: 'Standard wordlist attack' },
  { id: 1, name: 'Combination', desc: 'Combine two dictionaries' },
  { id: 3, name: 'Brute-Force', desc: 'Mask attack / Full keyspace' },
  { id: 6, name: 'Hybrid Dict + Mask', desc: 'Wordlist + Append mask' },
  { id: 7, name: 'Hybrid Mask + Dict', desc: 'Prepend mask + Wordlist' },
  { id: 9, name: 'Association', desc: 'Association attack' }
];

export const HASH_TYPES = [
  // --- Raw Hashes ---
  { id: '0', name: 'MD5', category: 'Raw Hash' },
  { id: '10', name: 'md5($pass.$salt)', category: 'Raw Hash' },
  { id: '20', name: 'md5($salt.$pass)', category: 'Raw Hash' },
  { id: '30', name: 'md5(unicode($pass).$salt)', category: 'Raw Hash' },
  { id: '40', name: 'md5($salt.unicode($pass))', category: 'Raw Hash' },
  { id: '50', name: 'HMAC-MD5 (key = $pass)', category: 'Raw Hash' },
  { id: '60', name: 'HMAC-MD5 (key = $salt)', category: 'Raw Hash' },
  { id: '70', name: 'md5(utf16le($pass))', category: 'Raw Hash' },
  { id: '100', name: 'SHA1', category: 'Raw Hash' },
  { id: '110', name: 'sha1($pass.$salt)', category: 'Raw Hash' },
  { id: '120', name: 'sha1($salt.$pass)', category: 'Raw Hash' },
  { id: '130', name: 'sha1(unicode($pass).$salt)', category: 'Raw Hash' },
  { id: '140', name: 'sha1($salt.unicode($pass))', category: 'Raw Hash' },
  { id: '150', name: 'HMAC-SHA1 (key = $pass)', category: 'Raw Hash' },
  { id: '160', name: 'HMAC-SHA1 (key = $salt)', category: 'Raw Hash' },
  { id: '170', name: 'sha1(utf16le($pass))', category: 'Raw Hash' },
  { id: '600', name: 'BLAKE2b-512', category: 'Raw Hash' },
  { id: '610', name: 'BLAKE2b-512($pass.$salt)', category: 'Raw Hash' },
  { id: '620', name: 'BLAKE2b-512($salt.$pass)', category: 'Raw Hash' },
  { id: '900', name: 'MD4', category: 'Raw Hash' },
  { id: '1300', name: 'SHA2-224', category: 'Raw Hash' },
  { id: '1310', name: 'sha224($pass.$salt)', category: 'Raw Hash' },
  { id: '1320', name: 'sha224($salt.$pass)', category: 'Raw Hash' },
  { id: '1400', name: 'SHA2-256', category: 'Raw Hash' },
  { id: '1410', name: 'sha256($pass.$salt)', category: 'Raw Hash' },
  { id: '1420', name: 'sha256($salt.$pass)', category: 'Raw Hash' },
  { id: '1430', name: 'sha256(unicode($pass).$salt)', category: 'Raw Hash' },
  { id: '1440', name: 'sha256($salt.unicode($pass))', category: 'Raw Hash' },
  { id: '1450', name: 'HMAC-SHA256 (key = $pass)', category: 'Raw Hash' },
  { id: '1460', name: 'HMAC-SHA256 (key = $salt)', category: 'Raw Hash' },
  { id: '1470', name: 'sha256(utf16le($pass))', category: 'Raw Hash' },
  { id: '1700', name: 'SHA2-512', category: 'Raw Hash' },
  { id: '1710', name: 'sha512($pass.$salt)', category: 'Raw Hash' },
  { id: '1720', name: 'sha512($salt.$pass)', category: 'Raw Hash' },
  { id: '1730', name: 'sha512(unicode($pass).$salt)', category: 'Raw Hash' },
  { id: '1740', name: 'sha512($salt.unicode($pass))', category: 'Raw Hash' },
  { id: '1750', name: 'HMAC-SHA512 (key = $pass)', category: 'Raw Hash' },
  { id: '1760', name: 'HMAC-SHA512 (key = $salt)', category: 'Raw Hash' },
  { id: '1770', name: 'sha512(utf16le($pass))', category: 'Raw Hash' },
  { id: '5000', name: 'SHA-3(Keccak)', category: 'Raw Hash' },
  { id: '5100', name: 'Half MD5', category: 'Raw Hash' },
  { id: '6000', name: 'RIPEMD-160', category: 'Raw Hash' },
  { id: '6100', name: 'Whirlpool', category: 'Raw Hash' },
  { id: '6900', name: 'GOST R 34.11-94', category: 'Raw Hash' },
  { id: '10800', name: 'SHA-384', category: 'Raw Hash' },
  { id: '11700', name: 'GOST R 34.11-2012 (Streebog) 256-bit', category: 'Raw Hash' },
  { id: '11800', name: 'GOST R 34.11-2012 (Streebog) 512-bit', category: 'Raw Hash' },
  { id: '17300', name: 'SHA3-224', category: 'Raw Hash' },
  { id: '17400', name: 'SHA3-256', category: 'Raw Hash' },
  { id: '17500', name: 'SHA3-384', category: 'Raw Hash' },
  { id: '17600', name: 'SHA3-512', category: 'Raw Hash' },
  { id: '20800', name: 'Keccak-224', category: 'Raw Hash' },
  { id: '20900', name: 'Keccak-256', category: 'Raw Hash' },
  { id: '21000', name: 'Keccak-384', category: 'Raw Hash' },
  { id: '21100', name: 'Keccak-512', category: 'Raw Hash' },

  // --- Windows / Operating Systems ---
  { id: '1000', name: 'NTLM', category: 'Windows' },
  { id: '3000', name: 'LM', category: 'Windows' },
  { id: '1100', name: 'Domain Cached Credentials (DCC), MS Cache', category: 'Windows' },
  { id: '2100', name: 'Domain Cached Credentials 2 (DCC2), MS Cache 2', category: 'Windows' },
  { id: '12800', name: 'MS-AzureSync PBKDF2-HMAC-SHA256', category: 'Windows' },
  { id: '19000', name: 'FRITZ!Box', category: 'Operating System' },
  { id: '19100', name: 'FRITZ!Box (User)', category: 'Operating System' },

  // --- Unix / Linux ---
  { id: '500', name: 'md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)', category: 'Unix' },
  { id: '1500', name: 'descrypt, DES (Unix), Traditional DES', category: 'Unix' },
  { id: '1600', name: 'Apache $apr1$ MD5, md5apr1, MD5 (APR)', category: 'Unix' },
  { id: '1800', name: 'sha512crypt $6$, SHA512 (Unix)', category: 'Unix' },
  { id: '3200', name: 'bcrypt $2*$, Blowfish (Unix)', category: 'Unix' },
  { id: '7400', name: 'sha256crypt $5$, SHA256 (Unix)', category: 'Unix' },
  { id: '6300', name: 'AIX {smd5}', category: 'Unix' },
  { id: '6400', name: 'AIX {ssha1}', category: 'Unix' },
  { id: '6500', name: 'AIX {ssha256}', category: 'Unix' },
  { id: '6600', name: 'AIX {ssha512}', category: 'Unix' },
  { id: '6700', name: 'AIX {ssha512}', category: 'Unix' },
  { id: '24100', name: 'Cisco-Type 7', category: 'Unix' },
  { id: '9200', name: 'Cisco-IOS $8$ (PBKDF2-SHA256)', category: 'Unix' },
  { id: '9300', name: 'Cisco-IOS $9$ (Scrypt)', category: 'Unix' },
  { id: '26700', name: 'Cisco-ISE Hashed Password (SHA256)', category: 'Unix' },
  { id: '7100', name: 'macOS v10.8+ (PBKDF2-SHA512)', category: 'Unix' },
  { id: '26500', name: 'iPhone Passcode (UID Key + Keybag)', category: 'Unix' },
  { id: '26600', name: 'iPhone Passcode (Fast, no UID Key)', category: 'Unix' },

  // --- Network ---
  { id: '2500', name: 'WPA-EAPOL-PBKDF2', category: 'Network' },
  { id: '22000', name: 'WPA-PBKDF2-PMKID+EAPOL', category: 'Network' },
  { id: '5500', name: 'NetNTLMv1 / NetNTLMv1+ESS', category: 'Network' },
  { id: '5600', name: 'NetNTLMv2', category: 'Network' },
  { id: '7300', name: 'IPMI2 RAKP HMAC-SHA1', category: 'Network' },
  { id: '7500', name: 'Kerberos 5, AS-REQ Pre-Auth', category: 'Network' },
  { id: '13100', name: 'Kerberos 5, TGS-REP', category: 'Network' },
  { id: '18200', name: 'Kerberos 5, AS-REP', category: 'Network' },
  { id: '19600', name: 'Kerberos 5, TGS-REP (17) AES128-CTS-HMAC-SHA1-96', category: 'Network' },
  { id: '19700', name: 'Kerberos 5, TGS-REP (18) AES256-CTS-HMAC-SHA1-96', category: 'Network' },
  { id: '19800', name: 'Kerberos 5, TGS-REP (23) RC4-HMAC', category: 'Network' },
  { id: '19900', name: 'Kerberos 5, Pre-Auth (17) AES128-CTS-HMAC-SHA1-96', category: 'Network' },
  { id: '20000', name: 'Kerberos 5, Pre-Auth (18) AES256-CTS-HMAC-SHA1-96', category: 'Network' },
  { id: '20100', name: 'Kerberos 5, Pre-Auth (23) RC4-HMAC', category: 'Network' },
  { id: '20200', name: 'Kerberos 5, AS-REP (17) AES128-CTS-HMAC-SHA1-96', category: 'Network' },
  { id: '20300', name: 'Kerberos 5, AS-REP (18) AES256-CTS-HMAC-SHA1-96', category: 'Network' },
  { id: '20400', name: 'Kerberos 5, AS-REP (23) RC4-HMAC', category: 'Network' },
  { id: '4800', name: 'iSCSI CHAP Authentication, MD5(RFC1994)', category: 'Network' },
  { id: '5300', name: 'IKE-PSK MD5', category: 'Network' },
  { id: '5400', name: 'IKE-PSK SHA1', category: 'Network' },
  { id: '10200', name: 'Cram MD5', category: 'Network' },
  { id: '16100', name: 'TACACS+', category: 'Network' },
  { id: '16200', name: 'Apple Secure Notes', category: 'Network' },
  { id: '16500', name: 'JWT (JSON Web Token)', category: 'Network' },
  { id: '22600', name: 'Telegram Desktop App Passcode (PBKDF2-HMAC-SHA1)', category: 'Network' },
  { id: '24600', name: 'SQLCipher', category: 'Network' },
  { id: '29200', name: 'Radmin 3', category: 'Network' },
  { id: '29400', name: 'TeamViewer', category: 'Network' },

  // --- Archives ---
  { id: '11600', name: '7-Zip', category: 'Archives' },
  { id: '12500', name: 'RAR3-hp', category: 'Archives' },
  { id: '13000', name: 'RAR5', category: 'Archives' },
  { id: '22500', name: 'Multi-Bitlocker', category: 'Archives' },
  { id: '13200', name: 'AxCrypt', category: 'Archives' },
  { id: '13300', name: 'AxCrypt 2', category: 'Archives' },
  { id: '13600', name: 'WinZip', category: 'Archives' },
  { id: '17200', name: 'PKZIP (Uncompressed)', category: 'Archives' },
  { id: '17210', name: 'PKZIP (Compressed)', category: 'Archives' },
  { id: '17220', name: 'PKZIP (Compressed Multi-File)', category: 'Archives' },
  { id: '17225', name: 'PKZIP (Mixed Multi-File)', category: 'Archives' },
  { id: '17230', name: 'PKZIP (Compressed Multi-File Checksum-Only)', category: 'Archives' },
  { id: '18900', name: 'Android Backup', category: 'Archives' },
  { id: '23000', name: 'Apple File System (APFS)', category: 'Archives' },

  // --- Documents ---
  { id: '9400', name: 'MS Office 2007', category: 'Documents' },
  { id: '9500', name: 'MS Office 2010', category: 'Documents' },
  { id: '9600', name: 'MS Office 2013', category: 'Documents' },
  { id: '25300', name: 'MS Office 2016 - SheetProtection', category: 'Documents' },
  { id: '9700', name: 'MS Office 2016', category: 'Documents' },
  { id: '9800', name: 'MS Office 2019', category: 'Documents' },
  { id: '10400', name: 'PDF 1.1 - 1.3 (Acrobat 2 - 4)', category: 'Documents' },
  { id: '10500', name: 'PDF 1.4 - 1.6 (Acrobat 5 - 8)', category: 'Documents' },
  { id: '10600', name: 'PDF 1.7 Level 3 (Acrobat 9)', category: 'Documents' },
  { id: '10700', name: 'PDF 1.7 Level 8 (Acrobat 10 - 11)', category: 'Documents' },
  { id: '29800', name: 'PDF 1.7 Level 3 (Acrobat 9) - Iteration Limit', category: 'Documents' },
  { id: '16900', name: 'Ansible Vault', category: 'Documents' },
  { id: '18600', name: 'Open Document Format (ODF) 1.2 (SHA-256)', category: 'Documents' },
  { id: '18400', name: 'Open Document Format (ODF) 1.1 (SHA-1)', category: 'Documents' },

  // --- Disk Encryption ---
  { id: '6211', name: 'TrueCrypt', category: 'Disk Encryption' },
  { id: '13711', name: 'VeraCrypt', category: 'Disk Encryption' },
  { id: '13721', name: 'VeraCrypt PIM', category: 'Disk Encryption' },
  { id: '13731', name: 'VeraCrypt 1.18a', category: 'Disk Encryption' },
  { id: '13741', name: 'VeraCrypt 1.18a PIM', category: 'Disk Encryption' },
  { id: '13751', name: 'VeraCrypt 1.18a Streebog', category: 'Disk Encryption' },
  { id: '13761', name: 'VeraCrypt 1.18a Streebog PIM', category: 'Disk Encryption' },
  { id: '22100', name: 'BitLocker', category: 'Disk Encryption' },
  { id: '14600', name: 'LUKS', category: 'Disk Encryption' },
  { id: '29300', name: 'LUKS2', category: 'Disk Encryption' },
  { id: '16700', name: 'FileVault 2', category: 'Disk Encryption' },
  { id: '27600', name: 'VirtualBox (PBKDF2-HMAC-SHA256)', category: 'Disk Encryption' },
  { id: '20500', name: 'PKCS#8 Private Keys (PBKDF2-HMAC-SHA1 + 3DES/AES)', category: 'Disk Encryption' },
  { id: '20510', name: 'PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES)', category: 'Disk Encryption' },

  // --- Database ---
  { id: '12', name: 'PostgreSQL', category: 'Database' },
  { id: '29500', name: 'PostgreSQL (Challenge-Response)', category: 'Database' },
  { id: '131', name: 'MSSQL (2000)', category: 'Database' },
  { id: '132', name: 'MSSQL (2005)', category: 'Database' },
  { id: '1731', name: 'MSSQL (2012, 2014)', category: 'Database' },
  { id: '200', name: 'MySQL323', category: 'Database' },
  { id: '300', name: 'MySQL4.1/MySQL5', category: 'Database' },
  { id: '3100', name: 'Oracle H: Type (Oracle 7+)', category: 'Database' },
  { id: '3610', name: 'Oracle S: Type (Oracle 11+)', category: 'Database' },
  { id: '11200', name: 'MySQL Challenge-Response Authentication (SHA1)', category: 'Database' },
  { id: '8000', name: 'Sybase ASE', category: 'Database' },
  { id: '24200', name: 'MongoDB (SCRAM-SHA-1)', category: 'Database' },
  { id: '24300', name: 'MongoDB (SCRAM-SHA-256)', category: 'Database' },

  // --- Cryptocurrency ---
  { id: '11300', name: 'Bitcoin/Litecoin wallet.dat', category: 'Cryptocurrency' },
  { id: '15700', name: 'Ethereum Wallet, SCRYPT', category: 'Cryptocurrency' },
  { id: '15600', name: 'Ethereum Wallet, PBKDF2-HMAC-SHA256', category: 'Cryptocurrency' },
  { id: '16300', name: 'Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256', category: 'Cryptocurrency' },
  { id: '22400', name: 'AES Wallet', category: 'Cryptocurrency' },
  { id: '26200', name: 'MetaMask Wallet', category: 'Cryptocurrency' },
  { id: '26300', name: 'Fortmatic Wallet', category: 'Cryptocurrency' },
  { id: '26400', name: 'Exodus Desktop Wallet', category: 'Cryptocurrency' },
  { id: '27400', name: 'VMware VMX (PBKDF2-HMAC-SHA256)', category: 'Cryptocurrency' },
  { id: '29600', name: 'Terra Station Wallet (AES256-GCM)', category: 'Cryptocurrency' },
  { id: '28300', name: 'LocalBitcoins', category: 'Cryptocurrency' },
  { id: '21000', name: 'Electrum Wallet (Salt-Type 4)', category: 'Cryptocurrency' },
  { id: '21700', name: 'Electrum Wallet (Salt-Type 5)', category: 'Cryptocurrency' },
  { id: '12700', name: 'Blockchain, My Wallet', category: 'Cryptocurrency' },
  { id: '15200', name: 'Blockchain, My Wallet, V2', category: 'Cryptocurrency' },
  { id: '18800', name: 'Blockchain, My Wallet, Second Password (SHA256)', category: 'Cryptocurrency' },
  { id: '28200', name: 'Exodus Web3 Wallet', category: 'Cryptocurrency' },

  // --- Password Managers ---
  { id: '6800', name: 'LastPass + LastPass Sniffed', category: 'Password Manager' },
  { id: '9000', name: 'Password Safe v2', category: 'Password Manager' },
  { id: '5200', name: 'Password Safe v3', category: 'Password Manager' },
  { id: '13400', name: 'KeePass 1 (AES/Twofish) and KeePass 2 (AES)', category: 'Password Manager' },
  { id: '29700', name: 'KeePass 1 (AES/Twofish) - Keyfile', category: 'Password Manager' },
  { id: '23400', name: 'Bitwarden', category: 'Password Manager' },
  { id: '28400', name: 'Bitwarden (v2)', category: 'Password Manager' },
  { id: '16800', name: '1Password, Agile Keychain', category: 'Password Manager' },
  { id: '16801', name: '1Password, Cloud Keychain', category: 'Password Manager' },
  { id: '26900', name: 'Dashlane', category: 'Password Manager' },

  // --- Generic KDF / Other ---
  { id: '400', name: 'phpass, WordPress (MD5), Joomla (MD5)', category: 'Generic KDF' },
  { id: '12000', name: 'PBKDF2-HMAC-MD5', category: 'Generic KDF' },
  { id: '12001', name: 'Atlassian (PBKDF2-HMAC-SHA1)', category: 'Generic KDF' },
  { id: '10900', name: 'PBKDF2-HMAC-SHA256', category: 'Generic KDF' },
  { id: '12100', name: 'PBKDF2-HMAC-SHA512', category: 'Generic KDF' },
  { id: '8900', name: 'scrypt', category: 'Generic KDF' },
  { id: '15100', name: 'Juniper/NetScreen/SSG (ScreenOS)', category: 'Generic KDF' },
  { id: '19200', name: 'ColdFusion 10+', category: 'Generic KDF' }
];